export const chaiClasses = {
    "chai-bg-red": { backgroundColor: "red" },
    "chai-bg-blue": { backgroundColor: "blue" },
    "chai-bg-green": { backgroundColor: "green" },
    "chai-bg-yellow": { backgroundColor: "yellow" },
    "chai-bg-gray": { backgroundColor: "#6b7280" },
    "chai-bg-white": { backgroundColor: "#ffffff" },
    "chai-bg-black": { backgroundColor: "#000000" },
    "chai-text-white": { color: "white" },
    "chai-text-black": { color: "black" },
    "chai-text-gray": { color: "#6b7280" },
    "chai-text-sm": { fontSize: "12px" },
    "chai-text-base": { fontSize: "16px" },
    "chai-text-lg": { fontSize: "18px" },
    "chai-text-xl": { fontSize: "20px" },
    "chai-font-bold": { fontWeight: "bold" },
    "chai-font-medium": { fontWeight: "500" },
    "chai-p-1": { padding: "4px" },
    "chai-p-2": { padding: "8px" },
    "chai-p-3": { padding: "12px" },
    "chai-p-4": { padding: "16px" },
    "chai-p-6": { padding: "24px" },
    "chai-m-1": { margin: "4px" },
    "chai-m-2": { margin: "8px" },
    "chai-m-4": { margin: "16px" },
    "chai-m-auto": { margin: "auto" },
    "chai-rounded-sm": { borderRadius: "4px" },
    "chai-rounded-md": { borderRadius: "8px" },
    "chai-rounded-lg": { borderRadius: "12px" },
    "chai-rounded-xl": { borderRadius: "16px" },
    "chai-rounded-full": { borderRadius: "9999px" },
    "chai-border": { border: "1px solid #e5e7eb" },
    "chai-border-2": { border: "2px solid #e5e7eb" },
    "chai-border-black": { borderColor: "#000" },
    "chai-border-white": { borderColor: "#fff" },
    "chai-w-full": { width: "100%" },
    "chai-w-screen": { width: "100vw" },
    "chai-w-fit": { width: "fit-content" },
    "chai-h-full": { height: "100%" },
    "chai-h-screen": { height: "100vh" },
    "chai-max-w-sm": { maxWidth: "640px" },
    "chai-max-w-md": { maxWidth: "768px" },
    "chai-max-w-lg": { maxWidth: "1024px" },
    "chai-flex": { display: "flex" },
    "chai-inline-flex": { display: "inline-flex" },
    "chai-flex-col": { flexDirection: "column" },
    "chai-flex-row": { flexDirection: "row" },
    "chai-flex-wrap": { flexWrap: "wrap" },
    "chai-items-center": { alignItems: "center" },
    "chai-items-start": { alignItems: "flex-start" },
    "chai-items-end": { alignItems: "flex-end" },
    "chai-justify-center": { justifyContent: "center" },
    "chai-justify-between": { justifyContent: "space-between" },
    "chai-justify-around": { justifyContent: "space-around" },
    "chai-gap-2": { gap: "8px" },
    "chai-gap-4": { gap: "16px" },
    "chai-relative": { position: "relative" },
    "chai-absolute": { position: "absolute" },
    "chai-fixed": { position: "fixed" },
    "chai-top-0": { top: "0" },
    "chai-left-0": { left: "0" },
    "chai-right-0": { right: "0" },
    "chai-bottom-0": { bottom: "0" },
    "chai-block": { display: "block" },
    "chai-inline-block": { display: "inline-block" },
    "chai-hidden": { display: "none" },
    "chai-shadow-sm": { boxShadow: "0 1px 2px rgba(0,0,0,0.1)" },
    "chai-shadow-md": { boxShadow: "0 4px 6px rgba(0,0,0,0.1)" },
    "chai-shadow-lg": { boxShadow: "0 10px 15px rgba(0,0,0,0.2)" },
    "chai-transition": { transition: "all 0.3s ease" },
    "chai-cursor-pointer": { cursor: "pointer" },
    "chai-text-center": { textAlign: "center" },
    "chai-text-left": { textAlign: "left" },
    "chai-text-right": { textAlign: "right" },
    "chai-overflow-hidden": { overflow: "hidden" },
    "chai-opacity-50": { opacity: "0.5" },
    "chai-opacity-75": { opacity: "0.75" },
    "chai-opacity-100": { opacity: "1" },
    "chai-animate-fade-in": {
        animation: "chai-fade-in 0.5s ease-in-out"
    },

    "chai-animate-slide-up": {
        animation: "chai-slide-up 0.4s ease-out"
    },

    "chai-animate-bounce": {
        animation: "chai-bounce 1s infinite"
    },

    "chai-animate-spin": {
        animation: "chai-spin 1s linear infinite"
    },
    "chai-card": {
        transition: "transform 0.3s ease, box-shadow 0.3s ease",
        transformStyle: "preserve-3d",
    },
    "chai-tilt-3d": {
        transition: "transform 0.15s ease-out",
        transformStyle: "preserve-3d",
        willChange: "transform",
    }
};
